version: "3"

services:

  postgres:
    image: postgres:latest
    restart: unless-stopped
    environment:
      POSTGRES_PASSWORD: ""
    networks:
       - net_clair

  clair:
    image: quay.io/coreos/clair-git:latest
    restart: unless-stopped
    depends_on:
      - postgres
    ports:
      - "6060-6061:6060-6061"
    volumes:
      - /tmp:/tmp
      - ./clair/clair_config:/config
    command: [-config, /config/config.yaml]
    networks:
      - net_clair

 # analyze:
 #   build: ./analyze
 #   restart: unless-stopped
 #   depends_on:
 #     - clair
 #     - postgres
 #   command: [-endpoint, "http://clair:6060", postgres]
 #   networks:
 #     - net_clair 

networks:
  net_clair:

